# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ecd9265675e0f9b460216f81cea10fd69d20f70b72bfec943411c00ce8741a562f94a39bf970af9e0acb227e530be093b2c3bfdc4b90018212c330e4c2d46a5b

test:
  secret_key_base: b9179a881d787db66b81a594f9eb65c0c1e9e023aabad658cf5fae575b993c9d09e99f260343eff346caedb072dcdbf90bb2b39fff8694e7899119419870400b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
